# Generated by Django 2.2.3 on 2019-07-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='men_100_meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
    ]
