# Generated by Django 2.2.3 on 2019-07-23 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_list', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='men_1500_meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_200_meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_400_meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_800_meter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_discus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_javelin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_Long_jump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='men_shot_put',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('student_name', models.CharField(max_length=20)),
                ('semister', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=10)),
            ],
        ),
    ]
