# Generated by Django 2.2.1 on 2019-08-02 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='player_name',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
