# Generated by Django 2.2.1 on 2019-08-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='desc',
            field=models.TextField(default='no name'),
            preserve_default=False,
        ),
    ]
