# Generated by Django 2.2.1 on 2019-08-27 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clubs',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('data', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Club_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('image', models.ImageField(upload_to='static/clubs/images')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Clubs')),
            ],
        ),
    ]
