# Generated by Django 2.2.1 on 2019-09-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20190827_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_image',
            name='image',
            field=models.ImageField(upload_to='mediaclubs/images'),
        ),
    ]
