# Generated by Django 2.2.1 on 2019-09-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20190910_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club_image',
            name='image',
            field=models.ImageField(upload_to='media/clubs/images'),
        ),
    ]
